export const TextureKeys = {
  player: 'player',
  playerHit: 'player-hit',
  playerBullet: 'player-bullet',
  enemyBullet: 'enemy-bullet',
  enemyChaser: 'enemy-chaser',
  enemyShooter: 'enemy-shooter',
  enemyDasher: 'enemy-dasher',
  enemyBoss: 'enemy-boss',
  doorHorizontal: 'door-horizontal',
  doorVertical: 'door-vertical',
  item: 'item',
  keyPickup: 'key-pickup',
  bombPickup: 'bomb-pickup',
  coinPickup: 'coin-pickup',
  chestPickup: 'chest-pickup',
  floorTile: 'floor-tile',
  wall: 'wall',
} as const;
